min_version: 1.10.10

pre-commit:
  jobs:
    - name: phpcbf
      glob:
        - "*.php"
        - "*.pdt"
      exclude:
        - vendor/*
      run: |
        vendor/bin/phpcbf --runtime-set php_version 70200 {staged_files}
