release:
  branches:
    - main

plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - - semantic-release-replace-plugin
    - replacements:
        - files:
            - config.json
          from: '"version": ".+?"'
          to: '"version": "${nextRelease.version}"'
          results:
            - file: config.json
              hasChanged: true
              numMatches: 1
              numReplacements: 1
          countMatches: true
  - - "@semantic-release/git"
    - assets:
        - config.json
      message: "chore: release ${nextRelease.version} [skip ci]"
  - "@semantic-release/github"
